agent {
    data_dir          = "/opt/spire/data"
    log_level         = "INFO"
    server_address    = "spire-server"
    server_port       = "8081"
    socket_path       = "/tmp/spire-sockets/workload_api.sock"
    trust_domain      = "ail.internal"
    insecure_bootstrap = true
    join_token        = "PLACEHOLDER_TOKEN"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
