services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-format=text"
      - "--log-level=info"
      - "--addr=0.0.0.0:8181"
      - "/policy/cloud_policy.rego"
    volumes:
      - ./policy:/policy

  immudb:
    image: codenotary/immudb:latest
    ports:
      - "3322:3322"
    environment:
      - IMMUDB_USER=${IMMUDB_USER}
      - IMMUDB_PASSWORD=${IMMUDB_PASSWORD}
    restart: unless-stopped
