/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />

// NOTE: This file should not be edited manually.
// It is auto-generated by Next.js on first `next dev` / `next build` run.
// See https://nextjs.org/docs/app/api-reference/config/typescript
