"""
AIL Ledger Client
=================
Thin HTTP client that routes all ImmuDB writes through the isolated verifier
service. The verifier holds immudb-py (gRPC SDK), keeping protobuf out of the
interceptor process and preserving the SPIFFE mTLS posture (ADR-0001).

Fail-closed: if the verifier is unreachable or returns verified: false, this
module raises, causing the middleware to return DENY rather than allowing
execution without a durable, verified audit record.

D21 (Phase 3a completion): every write carries VERIFIER_WRITE_KEY
(docs/adr/0011-verifier-authentication.md) - an unset or wrong key fails the
same way any other verifier error does (raises here, DENY at the middleware).

D22 (Phase 3b): every record this module writes is signed with the decision
service's own long-lived writer key before it is serialized, so the
signature is a field inside the record and is covered by the same inclusion
proof as every other byte. Fail-closed like everything else here except the
one subsystem D23 names: no writer key, or a signing failure, raises, and
the middleware returns DENY. A record that reached the ledger unsigned would
be a record no checker could attribute, and P3b-3's checker refuses one
rather than treating it as unsigned-and-fine - writing one would produce
evidence that cannot be verified rather than evidence that verifies weakly.
See docs/adr/0012-writer-signing-and-external-anchoring.md.
"""

import base64
import json
import logging
import os
import sys
import uuid
from datetime import datetime

import httpx
from dotenv import load_dotenv

# provenance/ is copied next to this module inside the decision service's
# image (decision_service/Dockerfile) and sits at the repo root in a
# checkout. Both candidates are added for the same reason
# decision_service/main.py adds two candidates for ledger/: the module has
# to import identically whether it is running in the container or being
# loaded directly by pytest from a checkout.
for _provenance_parent in (
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    os.path.dirname(os.path.abspath(__file__)),
):
    if os.path.isdir(os.path.join(_provenance_parent, "provenance")):
        if _provenance_parent not in sys.path:
            sys.path.insert(0, _provenance_parent)
        break

from provenance.record_signature import load_signing_key, sign_record  # noqa: E402

load_dotenv()

_VERIFIER_URL = os.getenv("VERIFIER_URL", "http://verifier:8003")

# D21 (Phase 3a completion): the verifier's own write-scoped credential
# (docs/adr/0011-verifier-authentication.md), independent of
# CONTROL_PLANE_WRITE_KEY. decision-service is provisioned with this key
# only, never VERIFIER_READ_KEY - the ledger client here only ever writes.
_VERIFIER_WRITE_KEY = os.getenv("VERIFIER_WRITE_KEY", "")

# P13-8 (Phase 1.3) introduced this as a single deployment-wide constant.
# D13/P2-3 (Phase 2) makes profile a property of the tool, not the
# deployment - log_tool_call now takes profile per call, from the caller's
# own registry (decision_service/schemas.py::TOOL_REGISTRY). This constant
# survives only as the default for callers that don't specify one (none do,
# in this codebase, but the control plane's own tombstone-writing path
# defines its own independent copy for the same reason it always has - see
# control_plane/main.py::RECORD_PROFILE).
RECORD_PROFILE = "observed"

# D22 (Phase 3b): the decision service's own writer key. A dedicated
# long-lived ECDSA P-256 pair, generated by `make keygen`, mounted read-only
# into this container and into no other except the control plane, which
# writes the erasure tombstone through the same rule. Deliberately NOT the
# service's SPIFFE SVID: docs/reports/spike-signing-anchor.md Question A
# returned NO-GO because an SVID-signed record stops verifying when the
# leaf's 24-hour TTL expires, confirmed across a real forced rotation in
# both directions.
_WRITER_SIGNING_KEY_PATH = os.getenv("AIL_WRITER_SIGNING_KEY", "")

_writer_keys = None


def get_writer_keys():
    """Load (signing key, verifying key) once, or raise.

    Raising rather than degrading is the point. An unsigned record is not a
    weaker record, it is a record tools/ail_verify_bundle.py refuses
    outright, so producing one would put unverifiable entries in a ledger
    whose whole claim is that its entries verify. Every other dependency in
    this project fails closed by explicit rule; the single documented
    exception is external anchoring (D23), and this is not that.
    """
    global _writer_keys
    if _writer_keys is None:
        if not _WRITER_SIGNING_KEY_PATH:
            raise RuntimeError(
                "AIL_WRITER_SIGNING_KEY is not set; this service cannot sign the "
                "records it writes (D22). Run 'make keygen' and mount the key."
            )
        if not os.path.exists(_WRITER_SIGNING_KEY_PATH):
            raise RuntimeError(
                f"AIL_WRITER_SIGNING_KEY points at {_WRITER_SIGNING_KEY_PATH}, which "
                "does not exist; refusing to write records nothing can attribute."
            )
        _writer_keys = load_signing_key(_WRITER_SIGNING_KEY_PATH)
        logging.info("Writer signing key loaded from %s", _WRITER_SIGNING_KEY_PATH)
    return _writer_keys


def _sign(log_entry: dict) -> dict:
    """Sign a record before it is serialized for the ledger write.

    Before, not after: the signature is a field in the record, so what goes
    to ImmuDB is the signed object and the inclusion proof covers the
    signature along with everything it signs.
    """
    signing_key, verifying_key = get_writer_keys()
    return sign_record(log_entry, signing_key, verifying_key)


class ImmuDBLedger:
    def __init__(self, verifier_url: str | None = None):
        self.verifier_url = verifier_url or _VERIFIER_URL
        self._check_health()

    def _check_health(self) -> None:
        try:
            with httpx.Client(timeout=5) as client:
                resp = client.get(f"{self.verifier_url}/health")
                resp.raise_for_status()
            logging.info("Verifier service reachable at %s", self.verifier_url)
        except Exception as exc:
            logging.error("Verifier service unreachable at %s: %s", self.verifier_url, exc)
            raise

    def log_tool_call(
        self,
        agent_id: str,
        tool_name: str,
        call_id: str,
        input_sha256: str,
        outcome_type: str,
        fault_class: str | None,
        policy_revision: str | None,
        reasons: list,
        content_state: str,
        profile: str = RECORD_PROFILE,
        exclusivity: str | None = None,
    ) -> int:
        """
        Write an outcome record to ImmuDB via the verifier's verifiedSet.

        The record carries a hash of the tool arguments, not the arguments
        themselves (D5) - the immutable ledger proves what was decided and
        that the input hashed to this value; the arguments live in the
        control plane's erasable content store, joined by call_id (D7,
        Phase 1.1 - minted at intercept, independent of ImmuDB's own tx
        numbering). content_state records whether that content write landed
        ("present") or was never attempted because tool_args wasn't
        dict-shaped ("unavailable") - "erased" is never written here, it is
        inferred at read time from content_state plus whether the
        content-store row still exists (control_plane/main.py::get_audit).

        profile and exclusivity (D13/P2-3, Phase 2) are supplied per call by
        the caller, from decision_service/schemas.py::TOOL_REGISTRY and
        resolve_exclusivity - never invented here, and never trusted from
        anything the tool's own config claims about itself. exclusivity is
        only ever non-None for a mediated tool; every record carries a
        profile, but only a mediated one also carries an exclusivity kind.

        The verifier performs inclusion-proof and consistency-proof verification
        on every write. A response with verified: false or any transport error
        raises so the middleware returns DENY rather than recording an entry
        that cannot be cryptographically confirmed.

        Returns the ImmuDB transaction ID on success.
        """
        timestamp = datetime.utcnow().isoformat()
        log_entry = {
            # D11 (Phase 1.2): every ledger record now carries an explicit
            # record_type so a consumer scanning a broader key range than
            # tool_call: (e.g. control_plane/main.py's content_erasure: scan)
            # discriminates on this field, not on key shape - "decision"
            # here, "content_erasure" for the tombstones erase_content
            # writes directly via the verifier (see control_plane/main.py).
            "record_type": "decision",
            "agent_id": agent_id,
            "timestamp": timestamp,
            "tool_name": tool_name,
            "call_id": call_id,
            "input_sha256": input_sha256,
            "outcome_type": outcome_type,
            "fault_class": fault_class,
            "policy_revision": policy_revision,
            "reasons": reasons,
            "content_state": content_state,
            "profile": profile,
        }
        if exclusivity is not None:
            log_entry["exclusivity"] = exclusivity
        # D22: signed here, before serialization, so the signature travels
        # inside the record rather than beside it.
        serialized  = json.dumps(_sign(log_entry), separators=(",", ":"))
        key         = f"tool_call:{agent_id}:{uuid.uuid4().hex}:{tool_name}"
        encoded_key = base64.b64encode(key.encode()).decode()
        encoded_val = base64.b64encode(serialized.encode()).decode()

        try:
            with httpx.Client(timeout=15) as client:
                resp = client.post(
                    f"{self.verifier_url}/write",
                    json={"key": encoded_key, "value": encoded_val},
                    headers={"X-API-Key": _VERIFIER_WRITE_KEY},
                )
                resp.raise_for_status()

            result = resp.json()
            if not result.get("verified"):
                detail = result.get("detail", "no detail")
                raise RuntimeError(f"Ledger write not verified by SDK: {detail}")

            tx_id = result["tx_id"]
            logging.info("Ledger write verified: tx=%d", tx_id)
            return tx_id

        except Exception as exc:
            logging.error("Verifier write failed for agent=%s tool=%s: %s", agent_id, tool_name, exc)
            raise

    def log_tool_intent(
        self,
        agent_id: str,
        tool_name: str,
        call_id: str,
        policy_revision: str,
        input_sha256: str,
        content_state: str,
        profile: str,
    ) -> int:
        """
        D16 (Phase 2 completion pass): written before a mediated tool's own
        execution runs, never after. record_type "decision_intent" is a
        distinct key namespace (tool_call_intent:, not tool_call:) from the
        completion record log_tool_call writes for the same call - the
        prefix is a scan partition only, the same discipline D11 already
        established for content_erasure: keys; classification still goes
        through record_type, not key shape alone.

        decision_service/main.py calls this immediately before
        _execute_vault_tool and refuses to execute at all if this raises -
        that refusal is enforced by the caller, not this method. A
        successful intent write followed by a completion write that later
        fails leaves an intent record with no matching completion record
        for its call_id - control_plane/main.py::get_audit detects that at
        read time (the same read-time-inference discipline content_state/
        payload_state already use) and surfaces it as execution_state
        "unknown": executed, outcome not durably recorded, rather than
        silently absent from /audit.

        Returns the ImmuDB transaction ID on success; raises on any
        failure, exactly like log_tool_call.
        """
        timestamp = datetime.utcnow().isoformat()
        log_entry = {
            "record_type": "decision_intent",
            "agent_id": agent_id,
            "timestamp": timestamp,
            "tool_name": tool_name,
            "call_id": call_id,
            "input_sha256": input_sha256,
            "policy_revision": policy_revision,
            "content_state": content_state,
            "profile": profile,
        }
        serialized  = json.dumps(_sign(log_entry), separators=(",", ":"))
        key         = f"tool_call_intent:{agent_id}:{uuid.uuid4().hex}:{tool_name}"
        encoded_key = base64.b64encode(key.encode()).decode()
        encoded_val = base64.b64encode(serialized.encode()).decode()

        try:
            with httpx.Client(timeout=15) as client:
                resp = client.post(
                    f"{self.verifier_url}/write",
                    json={"key": encoded_key, "value": encoded_val},
                    headers={"X-API-Key": _VERIFIER_WRITE_KEY},
                )
                resp.raise_for_status()

            result = resp.json()
            if not result.get("verified"):
                detail = result.get("detail", "no detail")
                raise RuntimeError(f"Intent write not verified by SDK: {detail}")

            tx_id = result["tx_id"]
            logging.info("Intent write verified: tx=%d call_id=%s", tx_id, call_id)
            return tx_id

        except Exception as exc:
            logging.error("Verifier intent-write failed for agent=%s tool=%s call_id=%s: %s", agent_id, tool_name, call_id, exc)
            raise


_ledger_instance = None


def get_ledger() -> ImmuDBLedger:
    global _ledger_instance
    if _ledger_instance is None:
        _ledger_instance = ImmuDBLedger()
    return _ledger_instance
